extends Node2D

class_name Game_Manager

enum PLAY_STATE {TEST, LINE_UP, POWER, ACCURACY, CASTING, CATCHING, CATCH_FAIL,
	CAST_SUCCEED, CATCH_SUCCEED, STANDUP_SITDOWN, WALKING, WRESTLING}
var cur_state : PLAY_STATE = PLAY_STATE.TEST
@export var lure_y_limit := -650
